export const CROWDFUNDING_CONTRACT = {
  address: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS as `0x${string}`,
  abi: [
    {
      inputs: [
        { internalType: "string", name: "_title", type: "string" },
        { internalType: "string", name: "_description", type: "string" },
        { internalType: "uint256", name: "_goalAmount", type: "uint256" },
        { internalType: "uint256", name: "period", type: "uint256" },
      ],
      name: "launchCampaign",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_campaignId", type: "uint256" }],
      name: "contribute",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_campaignId", type: "uint256" }],
      name: "closeCampaign",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_campaignId", type: "uint256" }],
      name: "withdrawFunds",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_campaignId", type: "uint256" }],
      name: "refund",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_campaignId", type: "uint256" }],
      name: "selectRandomWinner",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_campaignId", type: "uint256" }],
      name: "getContributors",
      outputs: [
        {
          components: [
            { internalType: "address", name: "sender", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "uint256", name: "timestamp", type: "uint256" },
          ],
          internalType: "struct CrowdFunding.Contribution[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "ethAmount", type: "uint256" }],
      name: "getEthPriceInUSD",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "campaigns",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "creator", type: "address" },
        { internalType: "address", name: "topSupporter", type: "address" },
        { internalType: "address", name: "firstContributor", type: "address" },
        { internalType: "address", name: "randomWinner", type: "address" },
        { internalType: "string", name: "title", type: "string" },
        { internalType: "string", name: "description", type: "string" },
        { internalType: "uint256", name: "goalAmount", type: "uint256" },
        { internalType: "uint256", name: "deadline", type: "uint256" },
        { internalType: "uint256", name: "amountRaised", type: "uint256" },
        { internalType: "uint256", name: "highestContribution", type: "uint256" },
        { internalType: "bool", name: "isOpen", type: "bool" },
        { internalType: "bool", name: "goalReached", type: "bool" },
        { internalType: "bool", name: "fundsClaimed", type: "bool" },
        { internalType: "bool", name: "randomWinnerSelected", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "campaignsCount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
  ],
} as const
