[profile.default]
optimizer = true
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
    "@chainlink-mix/contracts=lib/chainlink-mix/contracts",
    "forge-std=lib/forge-std/src",
    "ds-test=lib/ds-test/src"
]
